# Generated by Django 3.2.9 on 2021-12-29 12:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFlowLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('archived_on', models.DateTimeField(null=True)),
                ('profile_name', models.CharField(max_length=255)),
                ('contact_number', models.PositiveIntegerField()),
                ('messaged_by', models.CharField(choices=[('BOT', 'BOT'), ('CANDIDATE', 'CANDIDATE')], max_length=20)),
                ('message_status', models.CharField(default='sent', max_length=30)),
            ],
            options={
                'db_table': 'chat_flow_log',
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='FlowQueries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('archived_on', models.DateTimeField(null=True)),
                ('queries', models.TextField(max_length=255)),
                ('response', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'flow_queries',
                'ordering': ['-created_on'],
            },
        ),
    ]
